language: c
sudo: required
matrix:
    include:
        - os: osx
          osx_image: xcode6.4
        - os: osx
          osx_image: xcode7.3
        - os: osx
          osx_image: xcode8.3

install:
    - ./.travis/install-proj4.sh

script:
    - cmake .
    - make
    - ./test/projcl_test -CPU
