language: c
sudo: required
os: osx
matrix:
  osx_image:
    - xcode6.4
    - xcode7.3
    - xcode8.3
    - xcode9.4
    - xcode10.3
    - xcode11.6

install:
    - ./.travis/install-proj4.sh

script:
    - cmake . -DWITH_PROJ=ON
    - make
    - ./test/projcl_test -CPU
