
CC=clang

.PHONY: test

all:
	@mkdir -p obj
	$(CC) src/*.c -Iinclude -dynamiclib -o obj/libprojcl.dylib -framework Accelerate -framework OpenCL -Wall -Werror -mmacosx-version-min=10.8

test:
	@mkdir -p obj
	$(CC) test/*.c -Iinclude -o obj/projcl_test -Lobj -lprojcl -Wall -Werror
	./obj/projcl_test

test_proj4:
	@mkdir -p obj
	$(CC) test/*.c -Iinclude -o obj/projcl_test_proj4 -DHAVE_PROJ4 -Lobj -lprojcl -lproj -Wall -Werror
	./obj/projcl_test_proj4

clean:
	rm -rf obj
