name: build
on: [ push, pull_request ]
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [ gcc, gcc-10, clang ]
    steps:
      - name: Fetch public key
        run: wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
      - name: Add public key
        run: sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
      - name: Add repository
        run: sudo add-apt-repository "deb https://apt.repos.intel.com/oneapi all main"
      - name: Update repository
        run: sudo apt update
      - name: Install packages
        run: sudo apt install intel-oneapi-runtime-opencl opencl-c-headers libproj-dev
      - uses: actions/checkout@v2
      - name: Configure
        run: cmake . -DWITH_PROJ=ON
        env:
          CC: ${{ matrix.compiler }}
      - name: Make
        run: make
      - name: Test
        run: ./test/projcl_test -CPU
  macos:
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    steps:
      - name: Install Proj.4
        run: brew install proj
      - uses: actions/checkout@v2
      - name: Configure
        run: cmake . -DWITH_PROJ=ON
      - name: Make
        run: make
      - name: Test
        run: ./test/projcl_test -CPU
